services:
  - type: web
    name: cah-online
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /health
    healthCheckTimeout: 100
    healthCheckInterval: 15
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
