services:
  - type: web
    name: cah-online
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c config.py app:app
    healthCheckPath: /health
    healthCheckTimeout: 100
    healthCheckInterval: 15
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: EVENTLET_HUB
        value: "poll"
