services:
  - type: web
    name: cah-online
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python -m gunicorn 
      --worker-class eventlet 
      --workers 1 
      --threads 1
      --bind 0.0.0.0:$PORT 
      --timeout 300 
      --keep-alive 65 
      --log-level debug 
      --access-logfile - 
      --error-logfile - 
      wsgi:app
    healthCheckPath: /health
    healthCheckTimeout: 100
    healthCheckInterval: 15
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: EVENTLET_NONBLOCK
        value: "1"
